# Generated by Django 4.0.5 on 2022-08-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_ranjeet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranjeet',
        ),
    ]
