# Generated by Django 4.0.5 on 2022-09-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_admin_date_of_birth_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
