# Generated by Django 4.0.5 on 2022-09-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
