# Generated by Django 4.0.5 on 2022-09-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_remove_employee_password_alter_admin_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
