# Generated by Django 4.0.5 on 2022-09-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
