# Generated by Django 4.0.5 on 2022-09-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employee_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
