# Generated by Django 4.0.5 on 2022-09-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='forget_password_token',
            new_name='forget_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
