# Generated by Django 4.0.5 on 2022-09-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_rename_forget_password_token_profile_forget_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='email',
        ),
    ]
