# Generated by Django 4.0.5 on 2022-09-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_remove_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
