# Generated by Django 4.0.5 on 2022-09-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_employee_created_at_employee_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
    ]
