# Generated by Django 4.0.5 on 2022-09-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_employee_created_at_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
