# Generated by Django 4.0.5 on 2022-09-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_alter_employee_created_at_alter_employee_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
