# Generated by Django 4.0.5 on 2022-09-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
